HEADR = get_next_line.h
CC = gcc
CFLAGS = -Wall -Wextra -Werror
NAME = get_next_line.a
SRCS =	get_next_line.c \
		get_next_line_utils.c

OBJS = $(SRCS:.c=.o)

all: $(NAME)

$(NAME): $(OBJS) $(HEADR)
			@ar rcs $(NAME) $(OBJS)

%.o: %.c
			@$(CC) $(CFLAGS) -c $< -o $@

clean:
			@rm -f $(OBJS)

fclean: clean
			@rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
